language: node_js

# Test linux and osx
os:
    - linux
    - osx

# Test against all supported versions of Node.js
node_js:
    - '12'
    - '13'
    - '14'

cache:
    directories:
        - 'node_modules'
